version: 2.1

jobs:
  test:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: |
            ls
            pwd
  print_world:
    docker:
      - image: alpine:latest
    steps:
      - run: echo world

workflows:
  welcome:
    jobs:
      - test