version: 2.1

jobs:
  test:
    docker:
      - image: node:alpine

    working_directory: ~/hamada

    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: |
            echo "docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}"
            cd unit-testing
            npm install
            npm test

  print_world:
    docker:
      - image: alpine:latest
    steps:
      - run: echo world

workflows:
  welcome:
    jobs:
      - test