version: 2.1

jobs:
  print_hello:
    docker:
      - image: busybox:latest
    steps:
      # - checkout
      - run: echo hello
  print_world:
    docker:
      - image: alpine:latest
    steps:
      - run: echo world

workflows:
  welcome:
    jobs:
      - print_hello
      - print_world